### ISSUE TITLE
Does not work in Mozilla Firefox

### ISSUE THREAD

**Issue by Piya0612** [liuy97/ng2-input-autocomplete#1]
ng2-input-autocomplete does not work in Mozilla Firefox. The input loses focus.

**Comment by liuy97** [comment]
Confirm it. I will fix it as soon as possible.

**Comment by Piya0612** [comment]
Please. Thank you in advance.

**Comment by liuy97** [comment]
tested in Firefox https://liuy97.github.io/ng2-input-autocomplete/
