### ISSUE TITLE
Enter key wont select in the dropdown

### ISSUE THREAD

**Issue by jagabs** [liuy97/ng2-input-autocomplete#10]

**Comment by jagabs** [comment]
hi any follow up on this?

**Comment by liuy97** [comment]
no. I have not implemented it yet. I am still considering whether this is required. This is only for desktop apps, not mobil apps.
But i can implement it if you really need it.

**Comment by antajo** [comment]
Not working 0.3.3

**Comment by liuy97** [comment]
I will fix it as soon as possible

**Comment by liuy97** [comment]
I tested it in v0.3.4, and it works fine. https://stackblitz.com/edit/ng2-input-autocomplete

**Comment by antajo** [comment]
Not working in Angular 2 app :(
