### ISSUE TITLE
Not working on Chrome 73

### ISSUE THREAD

**Issue by GeniusGo** [liuy97/ng2-input-autocomplete#11]
In **Chrome 73**, ng2-input-autocomplete plugin doesn't allowed me to type anything. While it works fine in the Firefox.

While inspecting, I found that _<ng2-input-autocomplete>_ is not able to create. It just blinks and we need to keep the mouse button pressed on the input. It is harder to select option by this way.

**Steps to reproduce:**
1. Simply go to the URL: [https://stackblitz.com/edit/ng2-input-autocomplete](https://stackblitz.com/edit/ng2-input-autocomplete).
2. Try to type anything in input field with autocomplete.

**Comment by liuy97** [comment]
Thanks. I confirm this bug in Chrome 73. I will investigate it.
