### ISSUE TITLE
Change directive name to stop clash with HTML property autocomplete

### ISSUE THREAD

**Issue by ayyash** [liuy97/ng2-input-autocomplete#2]
I think you should change the directive "autocomplete" because HTML forms have that attribute 
https://www.w3schools.com/tags/att_form_autocomplete.asp
This caused a clash in one of my projects

**Comment by liuy97** [comment]
I don't think it's a bug in this component. Could you provide a plnkr demo?

What's the clash? What's your expected result?

**Comment by ayyash** [comment]
Well, I had a form with "autocomplete" set to true, so you can imagine the page that had that form kept giving me log errors (nothing in the UI, silent, but real), because the directive was called, and could not match the other attributes (like items, config...). It is always good practice to prefix directives and components so they don't clash with other project directives or HTML built in attributes. It isn't a bug, but a recommendation.

**Comment by liuy97** [comment]
@ayyash , Hope this fix can help you.

https://stackblitz.com/edit/ng2-input-autocomplete

**Comment by gavmck** [comment]
Also coming across this bug, turning the native autocomplete off is not a good option, this directive needs namespacing.

**Comment by liuy97** [comment]
OK, an additional directive name will be given.
