### ISSUE TITLE
Empty field. Please Help

### ISSUE THREAD

**Issue by devrvk** [liuy97/ng2-input-autocomplete#23]
Hello! Have a problem...after compile...I click on field but cursor enter on source field and i cann't type text on autocomplete input field :(

**Comment by liuy97** [comment]
hi, which angular version and browser do you use?

**Comment by devrvk** [comment]
Hello!

Angular 8.x

Google Crome with last update

вс, 27 сент. 2020 г., 12:28 liuy97 <notifications@github.com>:

**Comment by devrvk** [comment]
don't working `this.inputElement.focus();`

**Comment by liuy97** [comment]
Thanks. I will investigate it.

**Comment by liuy97** [comment]
Hi, I cannot reproduce this bug. But I release a rc version  (2.0.0-rc.0) with angular cli 8. Could you test it? @devrvk

**Comment by devrvk** [comment]
Oh, yes, i can test...

пн, 28 сент. 2020 г., 21:59 liuy97 <notifications@github.com>:

**Comment by devrvk** [comment]
Where i can download new release?

пн, 28 сент. 2020 г. в 22:13, Roman Kuzmenko <devrvk@gmail.com>:

**Comment by liuy97** [comment]
https://www.npmjs.com/package/ng2-input-autocomplete/v/2.0.0-rc.0

`npm i ng2-input-autocomplete@2.0.0-rc.0`

**Comment by devrvk** [comment]
That's works fine! Thank you! But I have last one question, how to dynamic
change items?

вт, 29 сент. 2020 г. в 10:34, liuy97 <notifications@github.com>:

**Comment by liuy97** [comment]
Great. It is simple in Angular. You can assign new array to items. See example in https://github.com/liuy97/ng2-input-autocomplete/blob/master/src/app/app.component.ts

```
search (term: string) {
    this.service.search(term).subscribe(e => this.wikiItems = e, error => console.log(error));
  }
```
