### ISSUE TITLE
ng build --prod

### ISSUE THREAD

**Issue by diegoferreirax** [liuy97/ng2-input-autocomplete#3]
When i make a build (ng build --prod) appear this error: 

ERROR in ./node_modules/ng2-input-autocomplete/ng2-input-autocompleteModule.ngfactory.js
Module not found: Error: Can't resolve 'ng2-input-autocompleteModule' in '/home/softkuka/Documentos/2 - Softkuka/2 - Testes/auto-complete/node_modules/ng2-input-autocomplete'
ERROR in ./src/app/app.module.ngfactory.js

In application he work fine, but i can't make a build --prod

**Comment by liuy97** [comment]
Thanks for your report. I have released a new version for fixing this bug.

**Comment by diegoferreirax** [comment]
Thank you very much!!!! Works fine
