### ISSUE TITLE
how can add multiple sourceField

### ISSUE THREAD

**Issue by smrmari** [liuy97/ng2-input-autocomplete#4]
i need autocomplete as the following method

name   age   Dob
xxxx      xx     xx-xx-xxxx

or
xxxx    xx      xx-xx-xxxx

how to make customization.

**Comment by liuy97** [comment]
This feature is not supported yet. But you can implement it in convert multiple fields to one string.

**Comment by liuy97** [comment]
it is better to handle this complicated case in typescript.
