### ISSUE TITLE
style the list css 

### ISSUE THREAD

**Issue by noririco** [liuy97/ng2-input-autocomplete#5]
any help with that ?

**Comment by liuy97** [comment]
You have to override css (":host /deep/") for now. I will add a custimized className as soon as possible.

**Comment by jagabs** [comment]
Theres a div in the outer part

![screen shot 2019-02-19 at 7 12 12 pm](https://user-images.githubusercontent.com/17292042/53010998-4df3f980-347a-11e9-8a2a-4ba7983a0b9d.png)
![screen shot 2019-02-19 at 7 12 17 pm](https://user-images.githubusercontent.com/17292042/53010999-4df3f980-347a-11e9-9fe4-3479fa086c44.png)
