### ISSUE TITLE
Can you show us example using reactive forms with formarray

### ISSUE THREAD

**Issue by jagabs** [liuy97/ng2-input-autocomplete#9]

**Comment by liuy97** [comment]
do you get any error? If you want to use this component in formarray, you can use example https://stackblitz.com/angular/odkjqqmqboy?file=src%2Fapp%2Fprofile-editor%2Fprofile-editor.component.html

you have to update value with index.

```
onSelect(item: any, i: number) {
    this.selectedItem = item;
    this.aliases.at(i).patchValue(item);
  }
```

**Comment by jagabs** [comment]
its okay now, i accessed it manually in on select. expenseFormGroup.controls["expenseDirectoryName"].setValue(item.expenseDirectoryName);
Thanks.

**Comment by liuy97** [comment]
it is nice that the issue gets resolved.
